### ISSUE TITLE
Unable to run tests

### ISSUE THREAD

**Issue by sampullman** [samatechtw/image-api#15]
Some tests are failing.

Command:
```bash
pnpm run test
```

All the endpoints in `AppModule.spec.ts`:
```
 FAIL  src/http/AppModule.spec.ts
  ● AppModule › POST /job

    thrown: "Exceeded timeout of 5000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      63 |   }
      64 |
    > 65 |   it('POST /job', async () => {
         |   ^
      66 |     const [fetched, jobId] = await doPost()
      67 |
      68 |     expect(fetched.ok).toEqual(true)

      at src/http/AppModule.spec.ts:65:3
      at Object.<anonymous> (src/http/AppModule.spec.ts:13:1)
```

Failing tests due to missing images in output: `serverImageHandlerWorker.spec.ts`, `PngquantOptimizer.spec.ts`, `SquooshOptimizer.spec.ts`, `SharpProcessor.spec.ts`, `SvgoOptimizer.spec.ts`

```
 FAIL  src/Worker/serverImageHandlerWorker.spec.ts
  ● serverImageHandlerWorker › handlePath() resize

    ENOENT: no such file or directory, open '/Users/sam/git/samatech/image-api/testOut/wtm_256x256_48x48.jpg'
```

**Comment by apolkingg8** [comment]
Sorry, I forgot one thing... the queue service is based on Redis, so we need a Redis service run on `localhost:6379`. After that, all the tests should pass on the local environment. I'll keep this issue because it should be motioned in README.

**Comment by sampullman** [comment]
That's ok, I figured it and am doing some refactoring now. I'll add the note to the README while I do that.

In the future we can run tests against Docker, but for now it's easy enough to just do `docker run --name redis -d -p 6379:6379 redis:6.0` before running.
