### ISSUE TITLE
Refactor project structure

### ISSUE THREAD

**Issue by apolkingg8** [samatechtw/image-api#28]
The current folder structure is partly separated by features, and partly by file type. The overall structure should update to be more consistent.

- [ ] Clear distinction between web-only, node-only, and shared modules
- [ ] Keep files related to the same feature in one module
- [ ] Organize utilities more consistently (?)

**Comment by sampullman** [comment]
I'm assuming this is done based on recent work. If not, feel free to re-open and add more detail.
