### ISSUE TITLE
Get job result endpoint

### ISSUE THREAD

**Issue by samatechtw** [samatechtw/image-api#4]
Implement an endpoint for retrieving a job result.

This does not cover the actual image processing/queuing/etc, only endpoint setup.

Example endpoint response in JSON format:
```json
{
  "status": "queued|progress|complete|fail",
  "assets": {
    "original": "<link>",
   "1080x900": "<link>",
   "720x600": "<link>",
  },
  "metadata": {}
}
```

**Comment by sampullman** [comment]
👌
